// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project
// developer：HF
#include "ui.h"
#include "ui_helpers.h"
#include "esp_log.h"

static const char *TAG = "ui";
///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
lv_group_t *g;
///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif


//********************************* */
/**
 * @brief handle knob event, and update the UI accordingly
 *
 * @param event
 */
void LVGL_knob_event(ui_knob_event_t event)
{
    if (lv_scr_act() != ui_main_screen)
        return;

    if (event == UI_KNOB_LEFT)
    {
        ui_main_screen_knob_rotate(-1);
    }
    else if (event == UI_KNOB_RIGHT)
    {
        ui_main_screen_knob_rotate(1);
    }
}

/**
 * @brief handle button event, and update the UI accordingly
 * 
 * @param event 
 */
void LVGL_button_event(ui_button_event_t event)
{
    if (lv_scr_act() != ui_main_screen)
        return;

    if (event == UI_BUTTON_SINGLE_CLICK)
    {
        ui_main_screen_knob_activate_selected();
    }
}


/**
 * @brief user modified ui init function, called in main.cpp
 *
 */
void ui_init(void)
{

    lv_disp_t *dispp = lv_disp_get_default();
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);

    lv_scr_load(lv_obj_create(NULL)); // 清理默认屏幕

    ui_splash_screen_init();
    ui_subscreen_1_init();
    ui_subscreen_2_init();
    ui_subscreen_3_init();
    ui_subscreen_4_init();
    ui_subscreen_5_init();
    
    ui____initial_actions0 = lv_obj_create(NULL);

    lv_disp_load_scr(ui_splash_screen); // only load the splash screen at startup
}
