// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_background(lv_event_t * e);
extern lv_obj_t * ui_background;
extern lv_obj_t * ui_Image1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
// CUSTOM VARIABLES

// SCREEN: ui_time
void ui_time_screen_init(void);
void ui_event_time(lv_event_t * e);
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_Roller1;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image4;
// CUSTOM VARIABLES

// SCREEN: ui_working
void ui_working_screen_init(void);
extern lv_obj_t * ui_working;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_Bar1;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1kaorou_png);    // assets/1kaorou.png
LV_IMG_DECLARE(ui_img_2kaoji_png);    // assets/2kaoji.png
LV_IMG_DECLARE(ui_img_3danta_png);    // assets/3danta.png
LV_IMG_DECLARE(ui_img_4pisa_png);    // assets/4pisa.png
LV_IMG_DECLARE(ui_img_5liupai_png);    // assets/5liupai.png
LV_IMG_DECLARE(ui_img_6shutiao_png);    // assets/6shutiao.png
LV_IMG_DECLARE(ui_img_black_png);    // assets/black.png
LV_IMG_DECLARE(ui_img_start_png);    // assets/start.png
LV_IMG_DECLARE(ui_img_1522004715);    // assets/set-time.png
LV_IMG_DECLARE(ui_img_362584155);    // assets/return-png.png
LV_IMG_DECLARE(ui_img_174066631);    // assets/ok-icon.png
LV_IMG_DECLARE(ui_img_min_png);    // assets/min.png
LV_IMG_DECLARE(ui_img_1620963198);    // assets/time-png.png


void   LVGL_knob_event(void *event);
void   LVGL_button_event(void *event);
// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
